Added logging when filesystem creation fails

diff --git a/zram-config b/zram-config
--- a/zram-config
+++ b/zram-config
@@ -80,7 +80,15 @@ createZdir() {
 			echo "dirMountOpt: ${dirMountOpt}; dirFsType: ${dirFSType}" >> "$ZLOG"
 			createZdevice || return 1
 
-			mke2fs -v -t "$dirFSType" "/dev/zram${RAM_DEV}" >> "$ZLOG" 2>&1 || return 1
+			echo "Executing command: mke2fs -v -t \"$dirFSType\" \"/dev/zram${RAM_DEV}\"" >> "$ZLOG"
+			mke2fs -v -t "$dirFSType" "/dev/zram${RAM_DEV}" >> "$ZLOG" 2>&1 
+			if [ $? != 0 ]; then 
+				# failed to create filesystem on zram device!
+				echo "Failed to create filesystem! Exiting! Echoing fdisk -l:" >> "$ZLOG"
+				fdisk -l >> "$ZLOG"
+				return 1
+			fi
+
 			mkdir -p "${ZDIR}/zram${RAM_DEV}" >> "$ZLOG" 2>&1 || return 1
 			mount --verbose --types "$dirFSType" -o "$dirMountOpt" "/dev/zram${RAM_DEV}" "${ZDIR}/zram${RAM_DEV}/" >> "$ZLOG" 2>&1 || return 1
 			mkdir -p "${ZDIR}/zram${RAM_DEV}/upper" "${ZDIR}/zram${RAM_DEV}/workdir" "$TARGET_DIR" >> "$ZLOG" 2>&1 || return 1
@@ -244,7 +252,7 @@ case "$1" in
 							BIND_DIR="$6"
 							OLDLOG_DIR="$7"
 							serviceConfiguration "stop"
-							createZdir
+							createZdir || echo "Failed to create zram device!" >> "$ZLOG"
 							;;
 					esac
 					;;
@@ -253,6 +261,9 @@ case "$1" in
 		if [[ $ZTAB_EMPTY == "true" ]]; then
 			echo "Configuration file '/etc/ztab' is empty and needs to be configured" >> "$ZLOG"
 			exit 1
+		fi
+		if [ ! -e /var/log/zram-config.log ]; then
+			ln -s "$ZLOG" "/var/log/zram-config.log"
 		fi
 		;;
 
